### PR TITLE
one-line install

### PR DESCRIPTION
**Pull request by danthe1st**
This pull request makes it possible to use systemd by typing just one line of code.

It downloads the install script using `curl` and pipes it into bash where it gets executed. The script then installs `git` along with all other dependencies, clones the repository and continues normally.

In order to test it, the command would be `curl "https://raw.githubusercontent.com/danthe1st/ubuntu-wsl2-systemd-script/master/ubuntu-wsl2-systemd-script.sh" | bash` until this pull request is merged as the script is only available in the fork.

### CODE REVIEW

**Comment by diddledan** [comment]
This pattern of `curl | bash` is a security-vulnerable method. It is not advised to _ever_ curl directly into bash!

**Comment by DamionGans** [comment]
I agree with @diddledan. Running scripts directly from internet while they can change at any time seems like a bad idea to me. I don't even trust myself at times. No merge, but thanks a lot for your contribution :)

**Comment by danthe1st** [comment]
I can fully understand that and I agree with this but I think it should be asded to the `README.md` that `git` needs to be installed.

**Comment by DamionGans** [comment]
Good one, will make a PR for that :)

**Pull request closed without merging**
